name: Docker Build
on:
  push:
    branches:
      - my-master
  workflow_dispatch:
jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t zzcgwu/gh-proxy:${{ github.sha }} .
          docker tag zzcgwu/gh-proxy:${{ github.sha }} zzcgwu/gh-proxy:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zzcgwu
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push Docker Image
        run: |
          docker push zzcgwu/gh-proxy:${{ github.sha }}
          docker push zzcgwu/gh-proxy:latest
